Add Russian language
HelloZeroNet/zeronet.io pull request #27
Opened 2017-10-26 17:22 UTC by imachug

Requesting review from somebody speaking Russian. Maybe @shift?

2017-12-13 20:11 UTC, GeoXiaN requested changes
Greetings!
I'm a Russian speaker and would apply these changes for the better flow of this description. Overall, great job!

2017-12-13 20:11 UTC, GeoXiaN commented on languages/ru.json
> +	"Windows, Linux, Mac supported": "Windows, Linux, Mac поддерживаются",
Windows, Linux, Mac поддерживаются -> Поддержка для Windows, Linux и Mac

2017-12-13 20:11 UTC, GeoXiaN commented on languages/ru.json
> +	"No single point of failure.": "Нет Ахиллесовой пяты.",
Нет Ахиллесовой пяты. -> Нет слабого звена.

2017-12-13 20:11 UTC, GeoXiaN commented on languages/ru.json
> +	"No configuration needed:": "Не нужна настройка:",
Не нужна настройка -> Без конфигурации сети.

2017-12-13 20:11 UTC, GeoXiaN commented on languages/ru.json
> +	"No passwords": "Нет паролей",
Нет паролей -> Без паролей.

2017-12-13 20:11 UTC, GeoXiaN commented on languages/ru.json
> +	"We believe in": "Мы верим в",
Мы верим в -> Наша вера в

2017-12-14 04:34 UTC, imachug commented
@GeoXiaN Looks better now.

2017-12-15 11:23 UTC, merged

2017-12-15 11:23 UTC, HelloZeroNet commented
Thanks!